# Usa a imagem oficial do Python, otimizada para containers
FROM python:3.10-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia e instala as dependências primeiro para aproveitar o cache do Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação
COPY api/ /app/api
COPY .env /app/

# O projeto usa uvicorn para rodar a API
# O CMD é o comando que será executado quando o container iniciar
# Usamos a porta 8000, padrão do uvicorn
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Expõe a porta (documentação, não afeta a execução)
EXPOSE 8000