# Usa a imagem oficial do MySQL 8
FROM mysql:8.0

# Define variáveis de ambiente para a configuração inicial do MySQL
# O DB_ROOT_PASSWORD é usado APENAS para a inicialização do container.
# O usuário da API será configurado pelo script SQL.
ENV MYSQL_ROOT_PASSWORD=sua_senha_root_segura
ENV MYSQL_DATABASE=wallet_homolog

# Copia o script SQL para a pasta de inicialização do MySQL.
# Arquivos nesta pasta são executados automaticamente na primeira vez que o container sobe.
COPY ./sql/DDL_Carteira_Digital.sql /docker-entrypoint-initdb.d/