CREATE TABLE IF NOT EXISTS DEPOSITO_SAQUE (
    id_movimento BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
    endereco_carteira VARCHAR(64) NOT NULL,
    id_moeda SMALLINT NOT NULL,
    tipo ENUM('DEPOSITO', 'SAQUE') NOT NULL,
    valor DECIMAL(18,8) NOT NULL DEFAULT 0.00000000,
    taxa DECIMAL(18,8) NOT NULL DEFAULT 0.00000000,
    data_hora DATETIME NOT NULL,

    FOREIGN KEY (endereco_carteira) REFERENCES CARTEIRA(endereco_carteira)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (id_moeda) REFERENCES MOEDA(id_moeda)
        ON DELETE CASCADE ON UPDATE CASCADE
)